/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-J3W4MV3959WCO29AalU-NS8U4AxHGm-qzZZxZJNLUZDkLB0ooV0kBFBuU3gOeOpS6hw9ERNF1X14s0hWcVj06L1f2zHZ99kfxP6-zV9A14YI597e34JgeJoY",
  "tt": "tt-1-OrUnpYToJPvTzljK39N2uCCbbyQYQ6E-BR471cU-8ks=",
  "version": "2020-11-20"
}

export default ebconfig;